package manifest

// clusterScopedKinds contains well-known cluster-scoped resource kinds.
var clusterScopedKinds = map[string]bool{
	"Namespace":                        true,
	"Node":                             true,
	"PersistentVolume":                 true,
	"CustomResourceDefinition":         true,
	"ClusterRole":                      true,
	"ClusterRoleBinding":               true,
	"StorageClass":                     true,
	"VolumeAttachment":                 true,
	"CSIDriver":                        true,
	"CSINode":                          true,
	"IngressClass":                     true,
	"PriorityClass":                    true,
	"RuntimeClass":                     true,
	"MutatingWebhookConfiguration":     true,
	"ValidatingWebhookConfiguration":   true,
	"ValidatingAdmissionPolicy":        true,
	"ValidatingAdmissionPolicyBinding": true,
	"APIService":                       true,
	"FlowSchema":                       true,
	"PriorityLevelConfiguration":       true,
	"PodSecurityPolicy":                true,
	"CertificateSigningRequest":        true,
	"SecurityContextConstraints":       true,
	"CiliumClusterwideNetworkPolicy":   true,
	"ClusterIssuer":                    true,
	"GatewayClass":                     true,
	"ClusterSecretStore":               true,
	"ClusterExternalSecret":            true,
	"ClusterPolicy":                    true,
	"ClusterTriggerAuthentication":     true,
}

// namespacedKinds contains well-known namespaced resource kinds.
var namespacedKinds = map[string]bool{
	"Pod":                     true,
	"Deployment":              true,
	"StatefulSet":             true,
	"DaemonSet":               true,
	"ReplicaSet":              true,
	"Job":                     true,
	"CronJob":                 true,
	"Service":                 true,
	"ConfigMap":               true,
	"Secret":                  true,
	"ServiceAccount":          true,
	"Role":                    true,
	"RoleBinding":             true,
	"Ingress":                 true,
	"NetworkPolicy":           true,
	"PersistentVolumeClaim":   true,
	"PodDisruptionBudget":     true,
	"HorizontalPodAutoscaler": true,
	"VerticalPodAutoscaler":   true,
	"ServiceMonitor":          true,
	"PodMonitor":              true,
	"PrometheusRule":          true,
	"Certificate":             true,
	"Issuer":                  true,
	"ExternalSecret":          true,
	"SecretStore":             true,
	"Endpoints":               true,
	"EndpointSlice":           true,
	"LimitRange":              true,
	"ResourceQuota":           true,
	"Lease":                   true,
	"CiliumNetworkPolicy":     true,
	"TriggerAuthentication":   true,
	"ScaledObject":            true,
}
