project_name: helm-datarobot
version: 2

builds:

- id: linux-build
  binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  no_unique_dist_dir: true
  main: .
  mod_timestamp: "{{ .CommitTimestamp }}"
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
    - amd64
    
- id: darwin-build
  binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  no_unique_dist_dir: true
  main: .
  mod_timestamp: "{{ .CommitTimestamp }}"
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  goarch:
    - amd64
    - arm64

archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: binary

sboms:
  - artifacts: binary

source:
  enabled: true

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
    - "sign-blob"
    - "--yes"
    - "--oidc-issuer=https://token.actions.githubusercontent.com"
    - "--output-signature=${signature}"
    - "--output-certificate=${certificate}"
    - "${artifact}"
    artifacts: all

changelog:
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
