name: "datarobot"
version: 0.0.30
usage: "DataRobot Helm Plugin"
description: "Tool for managing DataRobot Helm charts"
command: "$HELM_PLUGIN_DIR/bin/helm-datarobot-plugin"
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"

