name: "datarobot"
version: 0.0.8
usage: "DataRobot Helm Plugin"
description: "Tool for managing DataRobot Helm charts"
command: "$HELM_PLUGIN_DIR/helm-datarobot"
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"

