name: release

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".goreleaser.yml"
      - "plugin.yaml"
      - ".github/workflows/release.yml"

permissions:
  id-token: write
  packages: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@55dc4ee22412511ee8c3142cbea40418e6cec693 # v0.17.8

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'

      - name: bump
        run: |
          git config --global user.email "autobump@github.com"
          git config --global user.name "autobump"
          .github/scripts/bump.sh
          
      - name: release
        run: |
          echo $NEXT_VERSION
          git push --force
          git tag $NEXT_VERSION

      - uses: goreleaser/goreleaser-action@v6          # run goreleaser
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
