name: test
on:
  pull_request:
    paths:
      - "*"

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: "checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: helm build dependency
        run: |
          # This step is needed to make HELM_DATAROBOT_TEST_SKIP_DEPENDENCY_UPDATE=true work in unit tests
          helm dependency update testdata/test-chart3
          helm dependency update testdata/test-chart2
          helm dependency update testdata/test-chart1

      - name: run unit test
        run: |
          export GOPROXY=https://proxy.golang.org
          export HELM_DATAROBOT_TEST_SKIP_DEPENDENCY_UPDATE=true
          go run gotest.tools/gotestsum@v1.12.0 --format short-verbose --junitfile testResult_unit.xml
          ls -la .
          cat testResult_unit.xml

      - name: Docs
        run: |
          make docs
          if [[ $(git status --porcelain) ]]; then
            echo "Documentation is out of date, please update it"
            git diff
            exit 1
          fi

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: unit Tests
          path: "testResult_unit.xml"
          reporter: java-junit
          fail-on-error: true
