name: test
on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".goreleaser.yml"
      - "plugin.yaml"

permissions:
  contents: read
  pull-requests: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest


    steps:

      - name: "checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.3

      # - name: Docs
      #   run: |
      #     make docs
      #     if [[ $(git status --porcelain) ]]; then
      #       echo "Documentation is out of date, please update it"
      #       git diff
      #       exit 1
      #     fi

      - name: Run Docker Registry
        run: |
          mkdir -p  reg/certs reg/auth
          cd reg
          echo "reg_username:$2y$10$.9FIu6eRQkYl0xXMzZGjPuqTRfGX5oHScMEnojuXdB19AarIz/0Bm" > ./auth/htpasswd
          openssl req -newkey rsa:1024 -nodes -sha256 \
            -keyout ./certs/domain.key -x509 -days 365 \
            -out ./certs/domain.crt -subj "/CN=localhost"

          docker run -d -p 5000:5000 --name registry \
            -v ./certs:/certs \
            -v ./auth:/auth \
            -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
            -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
            -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
            -e REGISTRY_AUTH=htpasswd \
            -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
            -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
            registry:2

          sleep 5

          docker login -u reg_username -p reg_password localhost:5000

      - name: run unit test
        run: |
          make test
