name: test
on:
  pull_request:
    paths:
      - "*"

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: "checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: helm build dependency
        run: |
          # This step is needed to make HELM_DATAROBOT_TEST_SKIP_DEPENDENCY_UPDATE=true work in unit tests
          helm dependency update testdata/test-chart3
          helm dependency update testdata/test-chart2
          helm dependency update testdata/test-chart1

      - name: run unit test
        run: |
          export GOPROXY=https://proxy.golang.org
          export HELM_DATAROBOT_TEST_SKIP_DEPENDENCY_UPDATE=true
          go run gotest.tools/gotestsum@v1.12.0 --format short-verbose --junitfile testResult_unit.xml -- -count=1 -coverprofile cover.out

      - name: Static Analysis
        run: |
          golangci-lint run --out-format junit-xml . > testResult_lint.xml

      - name: Docs
        run: |
          make docs
          git status
          if [[ $(git status --porcelain) ]]; then
            echo "Changes"
            git config user.name "docs"
            git config user.email "auto-docs@github.com"
            git add . && git commit -am "[bot] Update docs" --signoff && git push
          else
            echo "No changes"
          fi

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: unit Tests
          path: "testResult_.*.xml"
          reporter: java-junit
          fail-on-error: true
